### ISSUE TITLE
FAP Download from Flipc

### ISSUE THREAD

**Issue by AC9DJ** [jamisonderek/flipboard#2]
Installed Momentum firmware on my Flipper and went to install the Flipboard app from Flipc.org and it appears the site has been down for some time. Is there a plan to provide an alternate download resource? Not sure building the FAPs using visual code or the likes is something I feel comfortable doing.

**Comment by jamisonderek** [comment]
I hope to start creating JavaScript for the FlopBoard in Momentum firmware, but the features of JavaScript are still catching up.  (Things like subghz sending the signal for a really Long time, lack of Infrared support, etc.)

I’ve made some updates and bug fixes recently, so I’ll see if MakeItHackin can publish new FAP files at https://github.com/MakeItHackin/FlipBoard/tree/main/fap_files  the current files are a couple weeks old.

Also, join my Discord server & let me know what features you would like.  https://discord.com/invite/NsjCvqwPAd
